version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: alteacare/article
    container_name: alteacare-article
    ports:
      - 8888:3000
    command: npm run dev